version: '3.1'
services:
  app:
    container_name: app-springboot
    image: app-springboot
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - dbpostgresql
  dbpostgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=internship
      - POSTGRES_USER=kn
      - POSTGRES_DB=store